services:
  api:
    image: api-app:test
    container_name: api
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      - internal

  test-db:
    image: test-db:latest
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: test_db_user
      POSTGRES_PASSWORD: test_db_password
    networks:
      - internal
      
networks:
  internal:
    name: internal
    external: true
