docs_dir: docs

# Project information
site_name: Refereezy Documentation
site_url: https://refereezy.smcardona.tech/docs/
site_description: Refereezy Digitalitzem l'esport, automatitzem actes, proporcionem seguiment en directe.
site_author: Refereezy

# Repository
repo_url: https://github.com/refereezy/refereezy-project/
repo_name: Refereezy
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2024-2025 <a href="https://refereezy.smcardona.tech">Refereezy</a>.

# Documentation and theme
theme:
  name: 'material'
  logo: 'https://i.postimg.cc/pXQNYB7R/4-sinfondo.png'
  features:
    - toc.integrate
    - toc.follow
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    - navigation.indexes
    - content.action.edit
    - content.tabs.link
    - content.code.copy
  palette:
    ## Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

# Options
extra:
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  icon:
    logo: 'material/robot-happy'
    repo: 'fontawesome/brands/gitlab'

extra_css:
  - css/hide_lang_links.css

# Google Analytics
#google_analytics:
#  - 'UA-XXXXXXXX-X'
#  - 'auto'

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          # format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      # emoji_index: !!python/name:materialx.emoji.twemoji
      # emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true

plugins:
  - search
    #  - enumerate-headings
  - glightbox
  - git-revision-date-localized:
      fallback_to_build_date: true

# TOC
nav:

  - Sobre nosaltres:
    - Overview: empresa/overview.md
    - Equip: empresa/team.md
    - Visió: empresa/visio.md
  
  - Introducció:
    - index.md
    - Primers Pasos: 
      - introduccio/getting-started.md


  - Aplicacions:
    - apps/index.md
    - Web de'Administració:
      - apps/website/overview.md
    - Web Pública:
      - apps/app_web/overview.md
    - Rellotge:
      - apps/app_rellotge/overview.md
    - Mòbil:
      - apps/app_mobile/overview.md
  
  #- API Documentation:
  #  - Overview: api/overview.md
  #  - Authentication: api/authentication.md
  #  - Endpoints: 
  #    - General: api/endpoints/general.md
  #    - Matches: api/endpoints/matches.md
  #    - Teams: api/endpoints/teams.md
  #    - Players: api/endpoints/players.md
  #    - Referees: api/endpoints/referees.md
  #    - Clock: api/endpoints/clock.md
  #  - Database Schema: api/database-schema.md
  #  - Realtime Features: api/realtime.md

  
  #- Desenvolupament:
  #  - Getting Started: development/getting-started.md
  #  - Environment Setup: development/environment-setup.md
  #  - Architecture: development/architecture.md
  #  - Docker Containers: development/docker.md
  #  - Firebase Integration: development/firebase.md
  #  - Contributing: development/contributing.md

  
  - Administració de Sistemes:
    - sysadmin/index.md
    - Estructura de xarxa:
      - sysadmin/estructura_xarxa.md
    - Packet Tracer:
      - sysadmin/packet_tracer/packet_tracer.md
    - Configuració equips físics: 
      - Router: sysadmin/sistemes/isard/router.md
      - Server 1: sysadmin/sistemes/isard/server1.md
      - Server 2: sysadmin/sistemes/isard/server2.md
    - Configuració al núvol: sysadmin/sistemes/aws/aws.md




