docs_dir: docs

# Project information
site_name: Refereezy Documentation
site_url: https://refereezy.smcardona.tech/docs/
site_description: Refereezy Digitalitzem l'esport, automatitzem actes, proporcionem seguiment en directe.
site_author: Refereezy

# Repository
repo_url: https://github.com/refereezy/refereezy-project/
repo_name: Refereezy
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2024-2025 <a href="https://refereezy.smcardona.tech">Refereezy</a>.

# Documentation and theme
theme:
  name: 'material'
  logo: 'images/logo.svg'
  features:
    - toc.integrate
    - toc.follow
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    - navigation.indexes
    - content.action.edit
    - content.tabs.link
    - content.code.copy
  palette:
    ## Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

# Options
extra:
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  icon:
    logo: 'material/robot-happy'
    repo: 'fontawesome/brands/gitlab'

extra_css:
  - css/hide_lang_links.css

# Google Analytics
#google_analytics:
#  - 'UA-XXXXXXXX-X'
#  - 'auto'

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          # format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      # emoji_index: !!python/name:materialx.emoji.twemoji
      # emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true

plugins:
  - search
    #  - enumerate-headings
  - glightbox
  - git-revision-date-localized:
      fallback_to_build_date: true

# TOC
nav:
  # Introduction

  - Sobre nosaltres:
    - English: empresa/overview.md
    - Català: empresa/empresa.ca.md
    - Español: empresa/empresa.es.md
  
  - Introducció:
    - index.md
    - Primer Pasos: 
      - getting-started.md
    - Característiques: 
      - features.md
  - Aplicacions:
    - apps/index.md
    - Watch App / Rellotge:
      - Overview: apps/app_rellotge/overview.md
      - Features: apps/app_rellotge/features.md
      - Technical Documentation: apps/app_rellotge/technical.md
      - User Manual: apps/app_rellotge/user-manual.md
      - Català: 
        - apps/app_rellotge/aplicacio-rellotge.ca.md
      - Español: apps/app_rellotge/aplicacio-rellotge.es.md
    
    - Mobile App / Mòbil:
      - Overview: apps/app_mobile/overview.md
      - Features: apps/app_mobile/features.md
      - Technical Documentation: apps/app_mobile/technical.md
      - User Manual: apps/app_mobile/user-manual.md
      - Català: apps/app_mobile/app-mobile.ca.md
    
    - App Pairing / Aparellament:
      - Overview: apps/app_pairing/overview.md
      - Mobile App Pairing: apps/app_pairing/mobile_pairing.md
      - Watch App Pairing: apps/app_pairing/watch_pairing.md
      - Communication Flow: apps/app_pairing/communication_flow.md
      - Technical Implementation: apps/app_pairing/technical_implementation.md
      - Troubleshooting: apps/app_pairing/pairing_troubleshooting.md
      - Català:
        - Overview: apps/app_pairing/overview.ca.md
        - Mobile App Pairing: apps/app_pairing/mobile_pairing.ca.md
        - Watch App Pairing: apps/app_pairing/watch_pairing.ca.md
        - Communication Flow: apps/app_pairing/communication_flow.ca.md
        - Technical Implementation: apps/app_pairing/technical_implementation.ca.md
        - Troubleshooting: apps/app_pairing/pairing_troubleshooting.ca.md
    
    - Web App / Web:
      - Overview: apps/app_web/overview.md
      - Features: apps/app_web/features.md
      - Technical Documentation: apps/app_web/technical.md
      - User Manual: apps/app_web/user-manual.md
      - Català: apps/app_web/app-web.ca.md
    
    - Website / Web Pública:
      - Overview: apps/website/overview.md
      - Features: apps/website/features.md
      - Technical Documentation: apps/website/technical.md
      - Català: apps/website/website.ca.md
  
  - API Documentation:
    - Overview: api/overview.md
    - Authentication: api/authentication.md
    - Endpoints: 
      - General: api/endpoints/general.md
      - Matches: api/endpoints/matches.md
      - Teams: api/endpoints/teams.md
      - Players: api/endpoints/players.md
      - Referees: api/endpoints/referees.md
      - Clock: api/endpoints/clock.md
    - Database Schema: api/database-schema.md
    - Realtime Features: api/realtime.md
    - Català: api/api.ca.md
  
  - Development / Desenvolupament:
    - Getting Started: development/getting-started.md
    - Environment Setup: development/environment-setup.md
    - Architecture: development/architecture.md
    - Docker Containers: development/docker.md
    - Firebase Integration: development/firebase.md
    - Contributing: development/contributing.md
    - Català: development/desenvolupament.ca.md
  
  - System Administration / Sistemes:
    - Infrastructure Overview: sysadmin/overview.md
    - Servers Configuration: 
      - General: sysadmin/servers/general.md
      - Server 1: sysadmin/servers/server1.md
      - Server 2: sysadmin/servers/server2.md
      - Mail Server: sysadmin/servers/mailserver.md
    - AWS Setup: sysadmin/aws.md
    - Network Configuration: sysadmin/network.md
    - Deployment: sysadmin/deployment.md
    - Català: sysadmin/sistemes.ca.md



