version: '3.8'

services:
  app:
    build:
     context: .
    container_name: api
    restart: unless-stopped
    ports:
      - "8080:80"
      - "443:443"  # HTTPS
    environment:
      - PORT=443
    networks:
      - internal
networks:
  internal:
    name: internal
    external: true

