version: '3.8'

services:
  api:
    image: api-app:latest
    container_name: api
    restart: unless-stopped
    ports:
      - "127.0.0.1:5000:5000"

    networks:
      - internal
      
networks:
  internal:
    name: internal
    external: true
