FROM python:3.10-slim

# Exposa el port per HTTPS
EXPOSE 443

# Set the working directory directly to /app/api
WORKDIR /app/api

# Copia les dependències (requirements.txt) dins del contenidor
COPY api/requirements.txt /app/api/requirements.txt

# Instal·la les dependències necessàries
RUN pip install --no-cache-dir -r requirements.txt

# Copia tota l'aplicació FastAPI dins del contenidor
COPY api /app/api
#COPY api/ssl /app/api/ssl

# Set appropriate permissions for SSL certificates
RUN chmod 600 /app/api/ssl/key.pem /app/api/ssl/fullchain.pem


CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "443", "--ssl-keyfile", "/app/api/ssl/key.pem", "--ssl-certfile", "/app/api/ssl/fullchain.pem"]
